### PR TITLE
1.3.357+support

### PR DESCRIPTION
**Pull request by lances101**
Folders restructured.
Updated Wox.Plugin and JSON NuGet references.
Current referenced Infrastructure DLL is now included in the repo.
Added a user notification indicating that to fully override Alt+Tab Wox needs to run as Administrator. 

**Bugfix:** query is now forced reset after Alt+Tab hook event

### CODE REVIEW

**Comment by bao-qian** [comment]
@lances101 this pr seems fix https://github.com/Wox-launcher/Wox/issues/1286

but could you explain why? it seem wox didn't changed the method signature, right?

**Comment by lances101** [comment]
@happlebao At compilation time Wox.Plugin.Switcheroo references a local copy of `Wox.Infrastructure` and uses `Wox.Infrastructure.Storage.PluginJsonStorage` from it to store its settings.

Now as to the issue itself, yes, as far as I know the signature of `PluginJsonStorage` did not change, but after commit https://github.com/Wox-launcher/Wox/commit/cb913fb5a4cfdfdb6520026da227ec43215f3591 `PluginJsonStorage` no longer inherits from `Storage`. Even when the user updated to 1.0.8, the compiled version was expecting to be able to link not only to `Wox.Infrastructure.PluginJsonStorage`, but also to `Wox.Infrastructure.Storage.Storage`.

**Comment by bao-qian** [comment]
do you have a copy of 1.0.8 zip?

**Comment by lances101** [comment]
I do not have a copy of 1.0.8. 

I do have a copy of 1.0.7 (compiled 23/06/2017)
https://github.com/Wox-launcher/Wox.Plugin.Switcheroo/releases/download/untagged-d402045b0b18ea812057/Wox.Plugin.Switcheroo-1.0.7.wox

**Comment by bao-qian** [comment]
It will give the same error right?

**Comment by lances101** [comment]
It should and it does (just checked it).

**Pull request merged**
